# php-fpm
fpm:
  image: wangmengyang/php:7.2.5-fpm
  ports:
    - "9000"
  volumes:
    - /etc/localtime:/etc/localtime
    - ./app/www:/usr/share/nginx/html
  env_file:
    - .env

# nginx
nginx:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - /etc/localtime:/etc/localtime
    - ./app/www:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    - ./app/log/nginx:/var/log/nginx
  links:
    - fpm:__DOCKER_PHP_FPM__